"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-6sg6=&q=j9alp1%#nnf)qh4nb%s%=m^+l_ckm2zq*=5x6t90eu'


INSTALLED_APPS = [
    'django.contrib.admin',         # obrigatório
    'django.contrib.auth',           # obrigatório
    'django.contrib.contenttypes',
    'django.contrib.sessions',       # obrigatório
    'django.contrib.messages',       # obrigatório
    'django.contrib.staticfiles',    # obrigatório
    'app_lu',
]

ALLOWED_HOSTS = []

STATIC_URL = '/static/'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Para usar SQLite
        'NAME': BASE_DIR / 'db.sqlite3',         # Caminho para o banco de dados
    }
}



DEBUG = True

ROOT_URLCONF = 'fatoracao_lu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # obrigatório
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # obrigatório
    'django.contrib.messages.middleware.MessageMiddleware',  # obrigatório
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
